import type { SourceSnippet } from "../shared/types.js";
import { createRequire } from "node:module";
import path from "node:path";
import { pathToFileURL } from "node:url";

type QvacSdk = {
  loadModel?: (opts: Record<string, unknown>) => Promise<string>;
  unloadModel?: (opts: { modelId: string }) => Promise<void>;
  completion?: (opts: Record<string, unknown>) => PromiseLike<unknown> | unknown;
  embed?: (opts: Record<string, unknown>) => PromiseLike<unknown> | unknown;
  LLAMA_3_2_1B_INST_Q4_0?: string;
  VERBOSITY?: Record<string, unknown>;
  [key: string]: unknown;
};

type CompletionMessage = {
  role: "system" | "user" | "assistant";
  content: string;
};

export type QvacConfig = {
  llmModel: string;
  embeddingModel: string;
  allowMock: boolean;
};

export class QvacRuntime {
  private sdk: QvacSdk | null = null;
  private modelId: string | null = null;
  private embeddingModelId: string | null = null;
  private mode: "qvac" | "mock" | "standby" | "unavailable" = "standby";

  constructor(private readonly config: QvacConfig) {
    if (config.allowMock) this.mode = "mock";
  }

  get status() {
    return {
      qvacMode: this.mode,
      llmModel: this.config.llmModel,
      embeddingModel: this.config.embeddingModel
    };
  }

  async initialize() {
    if (this.sdk || this.mode === "mock") return;
    if (this.config.allowMock) {
      this.mode = "mock";
      return;
    }
    try {
      this.sdk = await importQvacSdk();
      if (!this.sdk.loadModel || !this.sdk.completion) {
        throw new Error("@qvac/sdk did not expose loadModel/completion");
      }
      const modelSrc = resolveModelSource(this.sdk, this.config.llmModel) || this.sdk.LLAMA_3_2_1B_INST_Q4_0;
      if (!modelSrc) throw new Error("No QVAC model source configured");
      this.modelId = await this.sdk.loadModel({
        modelSrc,
        modelType: "llamacpp-completion",
        modelConfig: buildModelConfig(this.sdk, true),
        onProgress: (progress: unknown) => {
          process.stdout.write(`QVAC load progress: ${JSON.stringify(progress)}\n`);
        }
      });
      this.mode = "qvac";
    } catch (error) {
      this.mode = "unavailable";
      throw error;
    }
  }

  async complete(history: CompletionMessage[]) {
    await this.initialize();
    if (this.mode === "mock") return this.mockCompletion(history);
    if (!this.sdk?.completion || !this.modelId) {
      throw new Error("QVAC completion is unavailable");
    }

    const result = await this.sdk.completion({
      modelId: this.modelId,
      history,
      stream: true,
      generationParams: {
        temp: Number(process.env.QVAC_TEMP ?? 0.35),
        top_p: Number(process.env.QVAC_TOP_P ?? 0.9),
        top_k: Number(process.env.QVAC_TOP_K ?? 20),
        predict: Number(process.env.QVAC_PREDICT ?? 768)
      }
    });

    return sanitizeCompletion(await readCompletionText(result));
  }

  async embed(text: string) {
    await this.initialize();
    if (this.mode === "mock") return mockEmbedding(text);
    if (!this.sdk?.embed || !this.sdk.loadModel) {
      throw new Error("@qvac/sdk embed() is unavailable; install a QVAC embedding-capable SDK/runtime.");
    }
    if (!this.embeddingModelId) {
      const modelSrc = resolveModelSource(this.sdk, this.config.embeddingModel);
      if (!modelSrc) throw new Error("No QVAC embedding model source configured");
      this.embeddingModelId = await this.sdk.loadModel({
        modelSrc,
        modelType: "llamacpp-embedding",
        modelConfig: buildModelConfig(this.sdk, false),
        onProgress: (progress: unknown) => {
          process.stdout.write(`QVAC embedding load progress: ${JSON.stringify(progress)}\n`);
        }
      });
    }

    const result = await this.sdk.embed({
      modelId: this.embeddingModelId,
      text
    });
    return readEmbedding(result);
  }

  async unload() {
    if (this.sdk?.unloadModel && this.modelId) {
      await this.sdk.unloadModel({ modelId: this.modelId });
    }
    if (this.sdk?.unloadModel && this.embeddingModelId) {
      await this.sdk.unloadModel({ modelId: this.embeddingModelId });
    }
    this.modelId = null;
    this.embeddingModelId = null;
  }

  private mockCompletion(history: CompletionMessage[]) {
    const last = history[history.length - 1]?.content ?? "";
    if (last.includes("classify")) return "document_qa";
    if (last.includes("verify")) return "grounded, safety-bounded, cites local sources";
    const sourceLines = last
      .split("\n")
      .filter((line) => line.trim().startsWith("[source"))
      .slice(0, 3)
      .join("\n");
    return [
      "Mock QVAC mode is enabled for interface development only.",
      "The grounded answer should be generated by @qvac/sdk before submission.",
      sourceLines ? `Local source context considered:\n${sourceLines}` : "No local source context was supplied."
    ].join("\n\n");
  }
}

async function importQvacSdk() {
  const packageName = ["@qvac", "sdk"].join("/");
  const runtimeModules = process.env.QVAC_RUNTIME_NODE_MODULES;
  const flavor = process.env.QVAC_SDK_FLAVOR ?? "full";
  const importFromRuntime = async (specifier: string) => {
    if (!runtimeModules) return await import(specifier);
    const requireFromRuntime = createRequire(path.join(runtimeModules, "qvac-runtime.cjs"));
    const modulePath = requireFromRuntime.resolve(specifier);
    return await import(pathToFileURL(modulePath).href);
  };

  if (flavor === "bare") {
    try {
      const bareSdk = await importFromRuntime(["@qvac", "bare-sdk"].join("/"));
      const llm = await importFromRuntime("@qvac/bare-sdk/llamacpp-completion/plugin");
      const embedding = await importFromRuntime("@qvac/bare-sdk/llamacpp-embedding/plugin");
      return bareSdk.plugins([llm.llmPlugin, embedding.embeddingsPlugin]) as QvacSdk;
    } catch (error) {
      throw error;
    }
  }
  return (await importFromRuntime(packageName)) as QvacSdk;
}

function resolveModelSource(sdk: QvacSdk, configured: string) {
  const value = sdk[configured];
  if (typeof value === "string" || isRecord(value)) return value;
  return configured;
}

function buildModelConfig(sdk: QvacSdk, includeContext: boolean) {
  const verbosity = sdk.VERBOSITY;
  return {
    device: process.env.QVAC_DEVICE ?? "gpu",
    ...(includeContext ? { ctx_size: Number(process.env.QVAC_CTX_SIZE ?? 4096) } : {}),
    ...(isRecord(verbosity) && "ERROR" in verbosity ? { verbosity: verbosity.ERROR } : {})
  };
}

export function buildGroundedPrompt(question: string, sources: SourceSnippet[]) {
  const context = sources
    .map((source, index) => {
      return `[source ${index + 1}: ${source.documentName}, score ${source.score.toFixed(3)}]\n${source.text}`;
    })
    .join("\n\n");

  return [
    "You are QVAC MedPsy Privacy Desk, a local-first educational document assistant.",
    "Answer only from the supplied local sources. Cite sources inline as [source 1], [source 2], etc.",
    "Do not diagnose, prescribe treatment, or replace professional medical or mental-health care.",
    "If sources are insufficient, say what is missing.",
    "",
    `Question: ${question}`,
    "",
    "Local sources:",
    context || "No sources retrieved."
  ].join("\n");
}

async function readCompletionText(result: unknown) {
  if (typeof result === "string") return result;
  if (isRecord(result)) {
    if (typeof result.text === "string") return result.text;
    if (typeof result.content === "string") return result.content;
    if (typeof result.output === "string") return result.output;
    const tokenStream = result.tokenStream;
    if (isAsyncIterable(tokenStream)) {
      let text = "";
      for await (const token of tokenStream) text += String(token);
      return text;
    }
  }
  return JSON.stringify(result);
}

function readEmbedding(result: unknown) {
  if (Array.isArray(result) && result.every((value) => typeof value === "number")) return result;
  if (isRecord(result)) {
    const candidates = [result.embedding, result.embeddings, result.vector, result.data];
    for (const candidate of candidates) {
      if (Array.isArray(candidate) && candidate.every((value) => typeof value === "number")) return candidate;
      if (Array.isArray(candidate) && Array.isArray(candidate[0])) return candidate[0] as number[];
    }
  }
  throw new Error(`Unable to read embedding result from QVAC SDK: ${JSON.stringify(result).slice(0, 500)}`);
}

function sanitizeCompletion(text: string) {
  return text
    .replace(/<think>[\s\S]*?<\/think>/gi, "")
    .replace(/<think>[\s\S]*$/gi, "")
    .trim();
}

function mockEmbedding(text: string) {
  const vector = new Array<number>(96).fill(0);
  const words = text.toLowerCase().match(/[a-z0-9]+/g) ?? [];
  for (const word of words) {
    let hash = 2166136261;
    for (let index = 0; index < word.length; index += 1) {
      hash ^= word.charCodeAt(index);
      hash = Math.imul(hash, 16777619);
    }
    vector[Math.abs(hash) % vector.length] += 1;
  }
  const norm = Math.hypot(...vector) || 1;
  return vector.map((value) => value / norm);
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

function isAsyncIterable(value: unknown): value is AsyncIterable<unknown> {
  return isRecord(value) && Symbol.asyncIterator in value;
}
